=begin pod

=head1 NAME

Code::Snippets - Extract code snippets contained in a single file

=head1 SYNOPSIS

Main program:

    use Code::Snippets;

    my $CS = Code::Snippets.build(
        snips-file => ⟨some file containing the snippets⟩,
        snips-dir  => ⟨some directory in which to extract the snippets⟩,
        snip-bef   => ⟨regex matching what comes before a snippet⟩,
        snip-aft   => ⟨regex matching what comes after a snippet⟩,
        snip-id    => ⟨regex matching a snippet identifier⟩,
    );

A snippets file holds arbitrary text and snippets and could be
structured like this:

    ⟨Optional arbitrary text⟩
    ⟨A snippet⟩
    ⟨More arbitrary text⟩
    ⟨Another snippet⟩
    ⟨Another snippet⟩
    ⟨More arbitrary text⟩
    ⟨Another snippet⟩
    ⟨More arbitrary text⟩
    …

Each snippet is structured like this:

    ⟨What comes before the snippet, including the snippet id⟩
    ⟨The snippet itself⟩
    ⟨What comes after the snippet⟩

=head1 DESCRIPTION

When I started learning Raku, I often tried out short code snippets in
the REPL to see how they behaved. It took no time at all for those
snippets to become big enough to need to have them in a file I could
run independently. Then sometimes I wanted to try out stuff that
required more than one file (to see how 'use' statements were resolved
for example). I also liked to keep those snippet files around for
reference or for trying out different things later.

But I find it
rather inconvenient to have to rummage through dozens of tiny
snippets, each in its own file, to retrieve or modify code examples or
variants. This module helps me manage a bunch of more or less
independent snippets all in the same file and to on demand extract
them out to disk; some other code will need to take care of actually
running, compiling, whatever, the resulting extracted snippets.

=head1 Snippet files


=head1 Snippet name

A snippet has a name, which we will call a "snam"; for example,
"eg01". A code snippet often fits in a single file that can be run.
Here is an extremely trivial example of a Raku snippet:

    say "Hello world."


=head1 Snippet name

The simplest snippet id looks like this:

    ⟨snam⟩!&

For example:

    eg01!&

That would extract snippets to a file named 'eg01' in the 

    $CS.extract: :content(sub ($a, $b, $c) {$b}), @snam-globs;

These snippet id are special:

        Will skip the snippet completely.
    SKIP!&
    
        Will ignore this and all other snippets until the end of the
        file:
    STOP!&

Single file in top level:

    ⟨snam⟩!&    : ⟨snips-dir⟩/⟨snam⟩
    ⟨snam⟩!&.sh : ⟨snips-dir⟩/⟨snam⟩.sh

    sn0!&       : ⋯/sn0
    sn1!&.sh    : ⋯/sn1.sh
    snip3!/&

Files in subdir ⟨snam⟩:

    ⟨snam⟩!/&.raku     : ⟨snips-dir⟩/⟨snam⟩/⟨snam⟩.raku
    ⟨snam⟩/Baz.rakumod : ⟨snips-dir⟩/⟨snam⟩/Baz.rakumod

=head1 AUTHOR

Luc St-Louis <lucs@pobox.com>

=head1 COPYRIGHT AND LICENSE

Copyright 2015

This library is free software; you can redistribute it and/or modify
it under the Artistic License 2.0.

=end pod

